dist: xenial
language: python

cache:
  pip: true

stages:
  - name: test
    if: (branch = master) OR (type = pull_request AND head_branch = master)
  - name: deploy
    if: (tag IS present) OR (branch = master) OR (type = pull_request AND head_branch = master)

install: true

jobs:
  include:

    - stage: test
      python:
        - "3.6"
        - "3.7"
      script:
        - pip install . -q
        - python examples/basic.py

    - stage: deploy
      python:
        - "3.7"
      script:
        - true
      before_deploy:
        - echo "$TRAVIS_TAG" > VERSION
      deploy:
        provider: pypi
        user: $PYPI_USERNAME
        password: $PYPI_PASSWORD
        skip_cleanup: true
        on:
          tags: true
