name: kondo
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.7
  - pip
  - future
  - numpy
  - ruamel.yaml
  - pillow
  - pytorch=1.1.*
  - tensorflow=1.13.*
  - pip:
    - tb-nightly
